# Generated by Django 4.2 on 2023-04-22 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='upload_resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to='resume'),
            preserve_default=False,
        ),
    ]
