# Generated by Django 4.2 on 2023-04-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
